from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
ANALYSIS_PATHS = ROOT / 'legacy' / 'research' / 'scripts' / 'analysis_paths.py'
BASE_DIR = ROOT / 'legacy' / 'research_data' / 'ai 주가 변동 원인 분석'

AUTO_START = "# -- AUTO-GENERATED DOCUMENT PATHS START --"
AUTO_END = "# -- AUTO-GENERATED DOCUMENT PATHS END --"

DOC_DIRS = [
    BASE_DIR,
    BASE_DIR / "01_기획",
    BASE_DIR / "02_기준",
]


def iter_docs() -> list[Path]:
    docs: list[Path] = []
    for directory in DOC_DIRS:
        if not directory.exists():
            continue
        for path in sorted(directory.glob("*.md")):
            if path.name == "README.md" and path.parent == BASE_DIR:
                docs.append(path)
                continue
            if path.parent == BASE_DIR or path.parent in DOC_DIRS:
                docs.append(path)
    return sorted(set(docs), key=lambda p: p.relative_to(BASE_DIR).as_posix())


def path_expr(path: Path) -> str:
    rel = path.relative_to(BASE_DIR)
    if len(rel.parts) == 1:
        return f'BASE_DIR / "{rel.name}"'

    dir_name = rel.parts[0]
    file_name = rel.parts[-1]
    dir_var = {
        "01_기획": "PLAN_DIR",
        "02_기준": "REFERENCE_DIR",
    }.get(dir_name)
    if dir_var:
        return f'{dir_var} / "{file_name}"'
    return f'BASE_DIR / "{rel.as_posix()}"'


def build_block() -> str:
    lines = [
        AUTO_START,
        "# Generated by legacy/research/scripts/sync_analysis_paths.py. Do not edit this block manually.",
        "ANALYSIS_DOC_PATHS = {",
    ]
    for path in iter_docs():
        rel_key = path.relative_to(BASE_DIR).as_posix()
        lines.append(f'    "{rel_key}": {path_expr(path)},')
    lines.extend(["}", AUTO_END])
    return "\n".join(lines)


def replace_block(text: str, block: str) -> str:
    if AUTO_START in text and AUTO_END in text:
        before, rest = text.split(AUTO_START, 1)
        _, after = rest.split(AUTO_END, 1)
        return before.rstrip() + "\n\n" + block + after

    anchor = 'SUMMARY_DIR = BASE_DIR / "10_일일요약"'
    if anchor not in text:
        raise SystemExit(f"anchor not found in {ANALYSIS_PATHS}: {anchor}")
    return text.replace(anchor, anchor + "\n\n" + block, 1)


def main() -> None:
    parser = argparse.ArgumentParser(description="Sync stable analysis document paths into analysis_paths.py")
    parser.add_argument("--check", action="store_true", help="fail if analysis_paths.py is not up to date")
    args = parser.parse_args()

    text = ANALYSIS_PATHS.read_text(encoding="utf-8")
    updated = replace_block(text, build_block())
    if args.check:
        if updated != text:
            raise SystemExit("analysis_paths.py is not up to date. Run: rtk python legacy/research/scripts/sync_analysis_paths.py")
        print("analysis_paths.py is up to date")
        return

    if updated != text:
        ANALYSIS_PATHS.write_text(updated, encoding="utf-8")
        print(f"updated: {ANALYSIS_PATHS}")
    else:
        print(f"up-to-date: {ANALYSIS_PATHS}")


if __name__ == "__main__":
    main()
